// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneInc.Hackathon.ESBIntegrator.Data;

#nullable disable

namespace OneInc.Hackathon.ESBIntegrator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250116172054_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.ESBTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ESBTransactions");
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.MessageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasRetries")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetryInterval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c63493a-159c-4c92-8a1c-e4305d0d5870"),
                            HasRetries = true,
                            MaxRetries = 3,
                            Name = "Notification",
                            RetryInterval = "1M,2M,3M"
                        },
                        new
                        {
                            Id = new Guid("5643e06e-ff1e-4233-b9b4-a34fe62a17ec"),
                            HasRetries = true,
                            MaxRetries = 2,
                            Name = "Error",
                            RetryInterval = "5M,10M"
                        },
                        new
                        {
                            Id = new Guid("282e0058-6d1e-4812-8e2b-523fde31b04e"),
                            HasRetries = false,
                            MaxRetries = 0,
                            Name = "Broadcast",
                            RetryInterval = "1M"
                        });
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.NotifyEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpVerb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Endpoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20ce2306-b423-4b16-bc6c-db776412856e"),
                            Alias = "Notifications",
                            HttpVerb = "POST",
                            Url = "http://localhost:5101/api/webhook"
                        },
                        new
                        {
                            Id = new Guid("68409100-2390-4666-8c18-c5ef76d6cda6"),
                            Alias = "Webhooks",
                            HttpVerb = "POST",
                            Url = "http://localhost:5102/api/webhook"
                        },
                        new
                        {
                            Id = new Guid("eb7b263d-d38e-47b1-8277-bd2429025285"),
                            Alias = "Reporting",
                            HttpVerb = "POST",
                            Url = "http://localhost:5103/api/webhook"
                        });
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.OrphanMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingAttempts")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("OrphanMessages");
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e7795f8-d934-4482-adc4-89d5bc9cae63"),
                            EndpointId = new Guid("20ce2306-b423-4b16-bc6c-db776412856e"),
                            MessageType = "Notification"
                        },
                        new
                        {
                            Id = new Guid("3240ba42-c3fc-4d38-9307-1f1a6e1e3dfe"),
                            EndpointId = new Guid("20ce2306-b423-4b16-bc6c-db776412856e"),
                            MessageType = "Error"
                        },
                        new
                        {
                            Id = new Guid("3987be89-cca3-43e4-9654-c1be3b89d65d"),
                            EndpointId = new Guid("68409100-2390-4666-8c18-c5ef76d6cda6"),
                            MessageType = "Error"
                        },
                        new
                        {
                            Id = new Guid("fbf6afa8-b950-414b-9aea-6718ae2c364a"),
                            EndpointId = new Guid("20ce2306-b423-4b16-bc6c-db776412856e"),
                            MessageType = "Broadcast"
                        },
                        new
                        {
                            Id = new Guid("294676e2-c3ef-44d5-a84e-67080c7321f0"),
                            EndpointId = new Guid("68409100-2390-4666-8c18-c5ef76d6cda6"),
                            MessageType = "Broadcast"
                        },
                        new
                        {
                            Id = new Guid("48344421-da25-4c08-9135-d1738fc8ee66"),
                            EndpointId = new Guid("eb7b263d-d38e-47b1-8277-bd2429025285"),
                            MessageType = "Broadcast"
                        });
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.OrphanMessage", b =>
                {
                    b.HasOne("OneInc.Hackathon.ESBIntegrator.Models.ESBTransaction", "Transaction")
                        .WithMany("OrphanMessages")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("OneInc.Hackathon.ESBIntegrator.Models.ESBTransaction", b =>
                {
                    b.Navigation("OrphanMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
